; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env:yoradio-esp32s3n16r8-wrover]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp-wrover-kit
framework = arduino

board_build.f_cpu = 240000000L
board_build.f_flash = 40000000L
board_build.flash_mode = qio

board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

; Partíció táblázat
;board_build.partitions = default_16MB.csv      ; beépített
;board_build.partitions = partitions/partitions_huge_app_3mb_no_ota_1mb_spiffs.csv
board_build.partitions = partitions/partition_16MB_ota_spiffs.csv
;board_build.partitions = partitions\8MB__app-3mb_ota-8kb_SPIFFS-1.5mb.csv
board_build.filesystem = spiffs

build_flags =
    -DBOARD_HAS_PSRAM
    -fno-exceptions
    -Wall
    -Wextra
    -O2
    -fdiagnostics-color=always
    -DCORE_DEBUG_LEVEL=3
    -std=gnu++20
    -D LGFX_USE_PNG

build_unflags = -std=gnu++11

; Könyvtárak
lib_deps = 
    adafruit/Adafruit GFX Library@^1.12.3
    adafruit/Adafruit NeoPixel
    ;adafruit/Adafruit ILI9341@^1.6.2
    ;adafruit/RTClib@^2.1.4
    ;moononournation/GFX Library for Arduino@^1.4.7 ;only for Gution & GC9A01 onboard ESP
    ;adafruit/Adafruit CST8XX Library ;only for GC9A01 onboard ESP
 
upload_speed = 460800
upload_resetmethod = nodemcu
upload_protocol = esptool
board_upload.before_reset = default_reset
board_upload.after_reset = hard_reset

upload_flags =
    --before=default_reset
    --after=hard_reset
    --no-stub

monitor_speed = 460800
monitor_rts = 0
monitor_dtr = 0
